[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=42", "wheel"]

[project]
authors = [
  {name = "Vadim Kozyrevskiy", email = "vadikko2@mail.ru"},
  {name = "Dmitriy Kutlubaev", email = "kutlubaev00@mail.ru"},
  {name = "Nikita Kunov"}
]
dependencies = [
  "pydantic==2.*",
  "orjson==3.9.15",
  "aio-pika==9.3.0",
  "di[anyio]==0.79.2",
  "sqlalchemy[asyncio]==2.0.*",
  "retry-async==0.1.4"
]
description = "Python CQRS pattern implementation"
name = "python-cqrs"
readme = "README.md"
version = "0.0.5"

[project.optional-dependencies]
dev = [
  "pre-commit==3.8.0",
  "pyright==1.1.377",
  "ruff==0.6.2",
  # Tests
  "aiokafka==0.10.0",
  "pytest~=7.4.2",
  "pytest-asyncio~=0.21.1",
  "pytest-env==0.6.2",
  "python-dotenv==1.0.1",
  "cryptography==42.0.2",
  "asyncmy==0.2.9"
]
kafka = [
  "aiokafka==0.10.0"
]

[tool.pytest.ini_options]
addopts = "--junit-xml=report.xml"
asyncio_mode = "auto"
junit_family = "xunit1"
testpaths = [
  "tests"
]

[tool.setuptools.packages.find]
where = ["src"]
