"""Alembic migration autogenerated from the outbox metadata (issue #85).

The acceptance criteria of the issue is literally "a migration generated from
the CQRS metadata can be successfully applied to PostgreSQL", so the test
autogenerates the migration on a live connection, renders it as Alembic would
write it into a revision file and then executes it against the database.
"""

import typing

import pytest
import sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.asyncio import create_async_engine

import cqrs.sqlalchemy_types
from cqrs.outbox.sqlalchemy import Base

pytest.importorskip("alembic")

from alembic.autogenerate import produce_migrations, render_python_code  # noqa: E402
from alembic.migration import MigrationContext  # noqa: E402
from alembic.operations import Operations  # noqa: E402

from tests.integration.fixtures import (  # noqa: E402
    DATABASE_DSN_MYSQL,
    DATABASE_DSN_POSTGRESQL,
)

OUTBOX_TABLE = "outbox"
ENUM_TYPE_NAME = "eventstatus"

# The test database holds tables of other test modules too; autogenerate would
# render them as drops, so reflection is limited to the outbox table.
AUTOGENERATE_OPTS = {
    "include_name": lambda name, type_, parent_names: (name == OUTBOX_TABLE if type_ == "table" else True),
}


def render_outbox_migration(connection: sqlalchemy.Connection) -> typing.Text:
    """Renders the upgrade body Alembic would put into a revision file."""
    context = MigrationContext.configure(connection, opts=AUTOGENERATE_OPTS)
    migrations = produce_migrations(context, Base.metadata)
    upgrade_ops = migrations.upgrade_ops
    assert upgrade_ops is not None
    return render_python_code(upgrade_ops)


def apply_rendered_migration(
    connection: sqlalchemy.Connection,
    rendered: typing.Text,
) -> None:
    """Executes the rendered script the way an Alembic revision would.

    The rendered body is wrapped into an `upgrade()` function, exactly as
    `script.py.mako` does. The namespace mirrors a revision module: `op`, `sa`
    and — because autogenerate renders custom types with their module prefix —
    the `cqrs.sqlalchemy_types` module, which is what the documented
    `import cqrs.sqlalchemy_types` line in `alembic/script.py.mako` provides.
    """
    context = MigrationContext.configure(connection)
    namespace = {
        "op": Operations(context),
        "sa": sqlalchemy,
        "cqrs": cqrs,
    }
    exec(f"def upgrade() -> None:\n{rendered}", namespace)  # noqa: S102
    namespace["upgrade"]()


def has_pending_changes(connection: sqlalchemy.Connection) -> bool:
    context = MigrationContext.configure(connection, opts=AUTOGENERATE_OPTS)
    upgrade_ops = produce_migrations(context, Base.metadata).upgrade_ops
    assert upgrade_ops is not None
    return bool(upgrade_ops.as_diffs())


def drop_outbox_schema(connection: sqlalchemy.Connection) -> None:
    Base.metadata.drop_all(connection)
    if connection.dialect.name == "postgresql":
        connection.execute(sqlalchemy.text(f"DROP TYPE IF EXISTS {ENUM_TYPE_NAME}"))


class MigrationRunner:
    """Collects what happened while the autogenerated migration was applied."""

    def __init__(self) -> None:
        self.rendered: typing.Text = ""
        self.tables_after: typing.List[typing.Text] = []
        self.columns_after: typing.Dict[typing.Text, typing.Any] = {}
        self.pending_changes_after: bool = True

    def __call__(self, connection: sqlalchemy.Connection) -> None:
        drop_outbox_schema(connection)

        self.rendered = render_outbox_migration(connection)
        apply_rendered_migration(connection, self.rendered)

        inspector = sqlalchemy.inspect(connection)
        self.tables_after = inspector.get_table_names()
        self.columns_after = {column["name"]: column for column in inspector.get_columns(OUTBOX_TABLE)}
        self.pending_changes_after = has_pending_changes(connection)


async def run_migration(dsn: typing.Text) -> MigrationRunner:
    runner = MigrationRunner()
    engine = create_async_engine(dsn)
    try:
        async with engine.begin() as connection:
            await connection.run_sync(runner)
        return runner
    finally:
        # Always drop leftover schema — MySQL may have committed partial DDL
        # even when migration/inspection fails midway.
        try:
            async with engine.begin() as connection:
                await connection.run_sync(drop_outbox_schema)
        finally:
            await engine.dispose()


@pytest.fixture(scope="function")
async def postgres_migration() -> MigrationRunner:
    if not DATABASE_DSN_POSTGRESQL:
        pytest.skip("DATABASE_DSN_POSTGRESQL not set")
    return await run_migration(DATABASE_DSN_POSTGRESQL)


@pytest.fixture(scope="function")
async def mysql_migration() -> MigrationRunner:
    if not DATABASE_DSN_MYSQL:
        pytest.skip("DATABASE_DSN_MYSQL not set")
    return await run_migration(DATABASE_DSN_MYSQL)


class TestPostgresqlMigration:
    def test_rendered_script_has_no_binary_type(self, postgres_migration):
        """`sa.BINARY` is what used to break the migration with 'type binary does not exist'."""
        assert "sa.BINARY" not in postgres_migration.rendered

    def test_rendered_script_uses_public_types_module(self, postgres_migration):
        """Custom types are rendered with a module prefix, hence the documented import."""
        assert "cqrs.sqlalchemy_types.UUIDBinary()" in postgres_migration.rendered
        assert "cqrs.sqlalchemy_types.Binary16()" in postgres_migration.rendered

    def test_migration_is_applied(self, postgres_migration):
        assert OUTBOX_TABLE in postgres_migration.tables_after

    def test_binary_columns_are_native_postgresql_types(self, postgres_migration):
        columns = postgres_migration.columns_after

        assert isinstance(columns["event_id"]["type"], postgresql.UUID)
        assert isinstance(columns["event_id_bin"]["type"], sqlalchemy.LargeBinary)

    def test_applied_schema_matches_metadata(self, postgres_migration):
        """A second autogenerate run must not find anything left to do."""
        assert not postgres_migration.pending_changes_after


class TestMysqlMigration:
    def test_rendered_script_uses_public_types_module(self, mysql_migration):
        assert "cqrs.sqlalchemy_types.UUIDBinary()" in mysql_migration.rendered
        assert "cqrs.sqlalchemy_types.Binary16()" in mysql_migration.rendered

    def test_migration_is_applied(self, mysql_migration):
        assert OUTBOX_TABLE in mysql_migration.tables_after

    def test_binary_columns_stay_binary16(self, mysql_migration):
        """Backward compatibility: MySQL keeps the very same physical columns."""
        columns = mysql_migration.columns_after

        for name in ("event_id", "event_id_bin"):
            column_type = columns[name]["type"]

            assert isinstance(column_type, sqlalchemy.BINARY)
            assert column_type.length == 16

    def test_applied_schema_matches_metadata(self, mysql_migration):
        assert not mysql_migration.pending_changes_after
