"""DDL and value handling of the saga storage JSON column.

The `context` column of `SagaExecutionModel` was moved from `sqlalchemy.JSON` to
`cqrs.sqlalchemy_types.JSONType`. The type is an extension point only: by
default it must render exactly the DDL that `sqlalchemy.JSON` rendered before,
on every dialect. The reference DDL strings below were captured from the model
before the change and are compared as whole statements, which is the backward
compatibility criterion of the change.
"""

import json
import typing

import pytest
import sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from cqrs.saga.storage.sqlalchemy import (
    SAGA_EXECUTION_TABLE_NAME,
    SAGA_LOG_TABLE_NAME,
    Base,
)
from cqrs.sqlalchemy_types import (
    Binary16,
    DialectTypeHandler,
    JSONType,
    UUIDBinary,
)

REFERENCE_DDL: typing.Dict[typing.Text, typing.Tuple[typing.Text, ...]] = {
    "postgresql": (
        "CREATE TABLE {executions} ("
        " id UUID NOT NULL,"
        " name VARCHAR(255) NOT NULL,"
        " status sagastatus NOT NULL,"
        " context JSON NOT NULL,"
        " version INTEGER NOT NULL,"
        " created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,"
        " updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,"
        " recovery_attempts INTEGER DEFAULT 0 NOT NULL,"
        " PRIMARY KEY (id)"
        " )",
        "CREATE TABLE {logs} ("
        " id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
        " saga_id UUID NOT NULL,"
        " step_name VARCHAR(255) NOT NULL,"
        " action VARCHAR(50) NOT NULL,"
        " status sagastepstatus NOT NULL,"
        " details TEXT,"
        " created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,"
        " PRIMARY KEY (id),"
        " FOREIGN KEY(saga_id) REFERENCES {executions} (id)"
        " )",
    ),
    "mysql": (
        "CREATE TABLE {executions} ("
        " id CHAR(32) NOT NULL COMMENT 'Saga ID',"
        " name VARCHAR(255) NOT NULL COMMENT 'Saga Name',"
        " status ENUM('PENDING','RUNNING','COMPENSATING','COMPLETED','FAILED')"
        " NOT NULL COMMENT 'Current status of the saga',"
        " context JSON NOT NULL COMMENT 'Serialized context',"
        " version INTEGER NOT NULL COMMENT 'Optimistic locking version',"
        " created_at DATETIME NOT NULL COMMENT 'Creation timestamp' DEFAULT now(),"
        " updated_at DATETIME NOT NULL COMMENT 'Last update timestamp' DEFAULT now(),"
        " recovery_attempts INTEGER NOT NULL COMMENT 'Number of recovery attempts' DEFAULT 0,"
        " PRIMARY KEY (id)"
        " )",
        "CREATE TABLE {logs} ("
        " id BIGINT NOT NULL COMMENT 'Log ID' AUTO_INCREMENT,"
        " saga_id CHAR(32) NOT NULL COMMENT 'Saga ID',"
        " step_name VARCHAR(255) NOT NULL COMMENT 'Name of the step',"
        " action VARCHAR(50) NOT NULL COMMENT 'Action performed (act/compensate)',"
        " status ENUM('STARTED','COMPLETED','FAILED','COMPENSATED') NOT NULL COMMENT 'Status of the step',"
        " details TEXT COMMENT 'Additional details or error message',"
        " created_at DATETIME NOT NULL COMMENT 'Timestamp of the log entry' DEFAULT now(),"
        " PRIMARY KEY (id),"
        " FOREIGN KEY(saga_id) REFERENCES {executions} (id)"
        " )",
    ),
}


def dialect_by_name(name: typing.Text) -> typing.Any:
    """Returns a driverless dialect instance usable for DDL compilation."""
    return sqlalchemy.create_mock_engine(f"{name}://", executor=None).dialect


def normalize(ddl: typing.Text) -> typing.Text:
    """Collapses the pretty printing of `CreateTable` into a single line."""
    return " ".join(ddl.split())


def compile_saga_ddl(dialect_name: typing.Text) -> typing.Tuple[typing.Text, ...]:
    dialect = dialect_by_name(dialect_name)
    return tuple(normalize(str(CreateTable(table).compile(dialect=dialect))) for table in Base.metadata.sorted_tables)


def reference_ddl(dialect_name: typing.Text) -> typing.Tuple[typing.Text, ...]:
    return tuple(
        statement.format(
            executions=SAGA_EXECUTION_TABLE_NAME,
            logs=SAGA_LOG_TABLE_NAME,
        )
        for statement in REFERENCE_DDL[dialect_name]
    )


@pytest.fixture()
def restore_registries():
    """`register_dialect` mutates a class level registry, undo it afterwards."""
    saved = {
        Binary16: dict(Binary16._handlers),
        JSONType: dict(JSONType._handlers),
        UUIDBinary: dict(UUIDBinary._handlers),
    }
    yield
    for type_, handlers in saved.items():
        type_._handlers = handlers


class TestDefaultDDLIsUnchanged:
    """Nobody has to migrate an existing saga schema because of `JSONType`."""

    @pytest.mark.parametrize("dialect_name", ("postgresql", "mysql"))
    def test_ddl_matches_the_pre_change_reference(self, dialect_name: typing.Text):
        assert compile_saga_ddl(dialect_name) == reference_ddl(dialect_name)

    @pytest.mark.parametrize("dialect_name", ("postgresql", "mysql"))
    def test_context_column_is_plain_json(self, dialect_name: typing.Text):
        ddl = compile_saga_ddl(dialect_name)[0]

        assert "context JSON NOT NULL" in ddl
        assert "JSONB" not in ddl

    def test_unknown_dialect_falls_back_to_default_handler(self):
        assert JSONType.get_handler("postgresql") is JSONType.default_handler
        assert JSONType.get_handler("mysql") is JSONType.default_handler
        assert JSONType.get_handler("oracle") is JSONType.default_handler

    def test_sqlite_still_renders_json(self):
        assert "context JSON NOT NULL" in compile_saga_ddl("sqlite")[0]


class TestRegisterJsonb:
    def test_postgresql_switches_to_jsonb(self, restore_registries):
        JSONType.register_dialect(
            "postgresql",
            DialectTypeHandler(type_factory=lambda dialect: postgresql.JSONB()),
        )

        assert "context JSONB NOT NULL" in compile_saga_ddl("postgresql")[0]

    def test_other_dialects_are_not_affected(self, restore_registries):
        JSONType.register_dialect(
            "postgresql",
            DialectTypeHandler(type_factory=lambda dialect: postgresql.JSONB()),
        )

        assert compile_saga_ddl("mysql") == reference_ddl("mysql")

    def test_registry_is_restored_after_the_fixture(self):
        assert compile_saga_ddl("postgresql") == reference_ddl("postgresql")


class TestRegistryIsolation:
    def test_json_registration_does_not_leak_into_binary_types(
        self,
        restore_registries,
    ):
        handler = DialectTypeHandler(type_factory=lambda dialect: postgresql.JSONB())
        JSONType.register_dialect("postgresql", handler)

        assert JSONType.get_handler("postgresql") is handler
        assert Binary16.get_handler("postgresql") is not handler
        assert UUIDBinary.get_handler("postgresql") is not handler
        assert "event_id_bin BYTEA" in str(
            CreateTable(
                sqlalchemy.Table(
                    "probe",
                    sqlalchemy.MetaData(),
                    sqlalchemy.Column("event_id_bin", Binary16),
                ),
            ).compile(dialect=dialect_by_name("postgresql")),
        )

    def test_binary_registration_does_not_leak_into_json(self, restore_registries):
        handler = DialectTypeHandler(
            type_factory=lambda dialect: sqlalchemy.LargeBinary(16),
        )
        Binary16.register_dialect("postgresql", handler)
        UUIDBinary.register_dialect("postgresql", handler)

        assert JSONType.get_handler("postgresql") is JSONType.default_handler
        assert compile_saga_ddl("postgresql") == reference_ddl("postgresql")


CONTEXT = {
    "user_id": "1a2b",
    "attempts": 3,
    "flag": True,
    "nested": {"items": [1, 2, 3], "none": None},
    "unicode": "значение",
}


def apply_processors(type_: typing.Any, dialect: typing.Any, value: typing.Any) -> typing.Any:
    """Passes `value` through the bind and result processors of `type_`.

    Some drivers (psycopg2, for instance) deserialize JSON themselves and expose
    no result processor at all, so a missing processor means "value as is".
    """
    impl = type_.dialect_impl(dialect)
    bind = impl.bind_processor(dialect)
    result = impl.result_processor(dialect, None)
    bound = bind(value) if bind is not None else value
    return result(bound) if result is not None else bound


class TestValueRoundTrip:
    """`JSONType` adds no conversion of its own, it defers to the dialect."""

    @pytest.mark.parametrize("dialect_name", ("postgresql", "mysql", "sqlite"))
    def test_processors_behave_exactly_like_sqlalchemy_json(
        self,
        dialect_name: typing.Text,
    ):
        dialect = dialect_by_name(dialect_name)

        assert apply_processors(JSONType(), dialect, CONTEXT) == apply_processors(
            sqlalchemy.JSON(),
            dialect,
            CONTEXT,
        )

    @pytest.mark.parametrize("dialect_name", ("postgresql", "mysql", "sqlite"))
    def test_dict_is_serialized_to_json_text(self, dialect_name: typing.Text):
        dialect = dialect_by_name(dialect_name)
        impl = JSONType().dialect_impl(dialect)
        processor = impl.bind_processor(dialect)
        assert processor is not None

        bound = processor(CONTEXT)

        assert isinstance(bound, (str, bytes))
        assert json.loads(bound) == CONTEXT

    def test_jsonb_registration_keeps_serialization_working(
        self,
        restore_registries,
    ):
        JSONType.register_dialect(
            "postgresql",
            DialectTypeHandler(type_factory=lambda dialect: postgresql.JSONB()),
        )
        dialect = dialect_by_name("postgresql")
        processor = JSONType().dialect_impl(dialect).bind_processor(dialect)
        assert processor is not None

        bound = processor(CONTEXT)

        assert json.loads(bound) == CONTEXT

    def test_none_is_passed_through(self):
        dialect = dialect_by_name("postgresql")

        assert JSONType().process_bind_param(None, dialect) is None
        assert JSONType().process_result_value(None, dialect) is None


class TestDatabaseRoundTrip:
    """A real engine is the final word on serialization not being broken."""

    @pytest.fixture()
    def table(self) -> sqlalchemy.Table:
        return sqlalchemy.Table(
            "json_probe",
            sqlalchemy.MetaData(),
            sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
            sqlalchemy.Column("context", JSONType, nullable=False),
        )

    def test_dict_written_and_read_back_unchanged(self, table: sqlalchemy.Table):
        engine = sqlalchemy.create_engine("sqlite://")
        with engine.begin() as connection:
            table.metadata.create_all(connection)
            connection.execute(table.insert().values(id=1, context=CONTEXT))
            stored = connection.execute(sqlalchemy.select(table.c.context)).scalar_one()

        assert stored == CONTEXT
