"""DDL and value handling of the outbox `payload` column.

The column was moved from a plain `sqlalchemy.LargeBinary` to
`cqrs.sqlalchemy_types.PayloadBinary`. The type is an extension point only: by
default it must render exactly the DDL that `sqlalchemy.LargeBinary` rendered
before, on every supported dialect. The reference DDL strings below were
captured from the model before the change and are compared as whole
`CREATE TABLE` statements, which is the backward compatibility criterion.
"""

import typing

import pytest
import sqlalchemy
from sqlalchemy.dialects import mssql, mysql, postgresql, sqlite
from sqlalchemy.dialects.mssql import base as mssql_base
from sqlalchemy.dialects.mssql import pyodbc as mssql_pyodbc
from sqlalchemy.schema import CreateTable

from cqrs.outbox.sqlalchemy import OutboxModel
from cqrs.sqlalchemy_types import (
    Binary16,
    DialectTypeHandler,
    JSONType,
    PayloadBinary,
    UUIDBinary,
)

REFERENCE_DDL: typing.Dict[typing.Text, typing.Text] = {
    "postgresql": (
        "CREATE TABLE outbox ("
        " id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
        " event_id UUID NOT NULL,"
        " event_id_bin BYTEA NOT NULL,"
        " event_status eventstatus NOT NULL,"
        " flush_counter SMALLINT NOT NULL,"
        " event_name VARCHAR(255) NOT NULL,"
        " topic VARCHAR(255) NOT NULL,"
        " created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,"
        " payload BYTEA NOT NULL,"
        " PRIMARY KEY (id),"
        " CONSTRAINT event_id_unique_index UNIQUE (event_id_bin, event_name)"
        " )"
    ),
    "mysql": (
        "CREATE TABLE outbox ("
        " id BIGINT NOT NULL COMMENT 'Identity' AUTO_INCREMENT,"
        " event_id BINARY(16) NOT NULL COMMENT 'Event idempotency id',"
        " event_id_bin BINARY(16) NOT NULL COMMENT 'Event idempotency id in 16 bit presentation',"
        " event_status ENUM('NEW','PRODUCED','NOT_PRODUCED') NOT NULL COMMENT 'Event producing status',"
        " flush_counter SMALLINT NOT NULL COMMENT 'Event producing flush counter',"
        " event_name VARCHAR(255) NOT NULL COMMENT 'Event name',"
        " topic VARCHAR(255) NOT NULL COMMENT 'Event topic',"
        " created_at DATETIME NOT NULL COMMENT 'Event creation timestamp' DEFAULT now(),"
        " payload BLOB NOT NULL COMMENT 'Event payload',"
        " PRIMARY KEY (id),"
        " CONSTRAINT event_id_unique_index UNIQUE (event_id_bin, event_name)"
        " )"
    ),
    "sqlite": (
        "CREATE TABLE outbox ("
        " id BIGINT NOT NULL,"
        " event_id BLOB NOT NULL,"
        " event_id_bin BLOB NOT NULL,"
        " event_status VARCHAR(12) NOT NULL,"
        " flush_counter SMALLINT NOT NULL,"
        " event_name VARCHAR(255) NOT NULL,"
        " topic VARCHAR(255) NOT NULL,"
        " created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,"
        " payload BLOB NOT NULL,"
        " PRIMARY KEY (id),"
        " CONSTRAINT event_id_unique_index UNIQUE (event_id_bin, event_name)"
        " )"
    ),
}

DIALECTS = {
    "postgresql": postgresql.dialect,
    "mysql": mysql.dialect,
    "sqlite": sqlite.dialect,
}


def normalize(ddl: typing.Text) -> typing.Text:
    return " ".join(ddl.split())


def compile_outbox_ddl(dialect) -> typing.Text:
    return normalize(str(CreateTable(OutboxModel.__table__).compile(dialect=dialect)))


def payload_definition(dialect) -> typing.Text:
    for line in str(CreateTable(OutboxModel.__table__).compile(dialect=dialect)).splitlines():
        if line.strip().startswith("payload "):
            return normalize(line).rstrip(",")
    raise AssertionError("outbox DDL has no payload column")


@pytest.fixture
def clean_payload_registry():
    """Restores the `PayloadBinary` registry, otherwise it leaks into other tests."""
    saved = dict(PayloadBinary._handlers)
    yield
    PayloadBinary._handlers.clear()
    PayloadBinary._handlers.update(saved)


@pytest.mark.parametrize("dialect_name", sorted(REFERENCE_DDL))
def test_outbox_ddl_is_unchanged(dialect_name: typing.Text):
    assert compile_outbox_ddl(DIALECTS[dialect_name]()) == REFERENCE_DDL[dialect_name]


def test_payload_is_dialect_aware():
    assert isinstance(OutboxModel.__table__.c.payload.type, PayloadBinary)


def test_default_handler_renders_plain_large_binary():
    dialect = sqlite.dialect()
    assert isinstance(
        PayloadBinary.get_handler(dialect.name).type_factory(dialect),
        sqlalchemy.LargeBinary,
    )
    assert PayloadBinary.get_handler(dialect.name) is PayloadBinary.default_handler


def test_driver_colspecs_are_applied():
    """`load_dialect_impl` goes through `type_descriptor`, so a driver may substitute its own type.

    The driverless `MSDialect` has no `LargeBinary` colspec and renders the legacy
    `IMAGE`; the pyodbc dialect maps `LargeBinary` to its own `VARBINARY` and
    renders `VARBINARY(max)` without any registration at all.
    """
    assert payload_definition(mssql_base.MSDialect()) == "payload IMAGE NOT NULL"
    assert payload_definition(mssql_pyodbc.dialect()) == "payload VARBINARY(max) NOT NULL"


def test_mssql_registration_overrides_ddl(clean_payload_registry):
    # Before the registration the driverless dialect still yields the legacy IMAGE.
    assert payload_definition(mssql_base.MSDialect()) == "payload IMAGE NOT NULL"

    PayloadBinary.register_dialect(
        "mssql",
        DialectTypeHandler(type_factory=lambda dialect: mssql.VARBINARY("max")),
    )

    for dialect in (mssql_pyodbc.dialect(), mssql_base.MSDialect()):
        definition = payload_definition(dialect)
        assert definition == "payload VARBINARY(max) NOT NULL"
        assert "IMAGE" not in definition

    for dialect_name in ("postgresql", "mysql"):
        assert compile_outbox_ddl(DIALECTS[dialect_name]()) == REFERENCE_DDL[dialect_name]


def test_registration_is_reverted_by_fixture():
    assert "mssql" not in PayloadBinary._handlers
    assert payload_definition(mssql_base.MSDialect()) == "payload IMAGE NOT NULL"


def test_registry_isolation_from_other_types(clean_payload_registry):
    handler = DialectTypeHandler(type_factory=lambda dialect: mssql.VARBINARY("max"))
    PayloadBinary.register_dialect("mssql", handler)

    for other in (UUIDBinary, Binary16, JSONType):
        assert other.get_handler("mssql") is other.default_handler
        assert "mssql" not in other._handlers


def test_other_types_do_not_leak_into_payload():
    assert PayloadBinary.get_handler("postgresql") is PayloadBinary.default_handler
    assert PayloadBinary.get_handler("mysql") is PayloadBinary.default_handler
    assert UUIDBinary.get_handler("postgresql") is not UUIDBinary.default_handler
    assert Binary16.get_handler("postgresql") is not Binary16.default_handler


@pytest.mark.parametrize(
    "value",
    [b"", b"\x00", b"payload", b"\x00\x01\x02\xff", bytes(range(256)), None],
)
def test_bind_and_result_round_trip(value):
    payload_type = PayloadBinary()
    dialect = sqlite.dialect()

    bound = payload_type.process_bind_param(value, dialect)
    assert bound == value
    assert payload_type.process_result_value(bound, dialect) == value


def test_sqlite_insert_select_round_trip():
    metadata = sqlalchemy.MetaData()
    table = sqlalchemy.Table(
        "payload_round_trip",
        metadata,
        sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
        sqlalchemy.Column("payload", PayloadBinary, nullable=True),
    )
    values = [b"", b"\x00\x01\x02\xff", bytes(range(256)), None]

    engine = sqlalchemy.create_engine("sqlite+pysqlite:///:memory:")
    try:
        with engine.begin() as connection:
            metadata.create_all(connection)
            connection.execute(
                table.insert(),
                [{"id": index, "payload": value} for index, value in enumerate(values)],
            )
            stored = (
                connection.execute(
                    sqlalchemy.select(table.c.payload).order_by(table.c.id),
                )
                .scalars()
                .all()
            )
    finally:
        engine.dispose()

    assert list(stored) == values
